name: 'gsheet-slack-logger'
description: 'Get your slack log and generate google sheet'
inputs:
  timezone:
    required: true
    description: 'your current timezone'
    default: 'Asia/Tokyo'
  slack-token:
    required: true
    description: 'slack bot token with required scopes'
  google-client-email:
    required: true
    description: 'email of google service account'
  google-private-key:
    required: true
    description: 'private_key for google service account'
  folder-id:
    required: true
    description: 'google drive folder id'
  year:
    required: false
    description: 'target year'
  month:
    required: false
    description: 'target month'
runs:
  using: 'docker'
  image: 'Dockerfile'
